[package]
name = "rtp"
version = "0.1.0"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]

[dependencies]
trackable = "0.1"
handy_async = "0.2"
rust-crypto = "0.2"
num = "0.1"
fixedbitset = "0.1"

[dev-dependencies]
clap = "2"
fibers = "0.1"
futures = "0.1"
